"use client";

import { useState } from "react";
import { cancelVoidedOrderAction } from "@/app/(protected)/orders/actions";
import { rebuildExceptionQueueAction } from "./actions";

export function ExceptionAction({ orderId, invoice, issueCode, productId, productSku, openDemand, queueUnits, reservationUnits, containerUnits, shippedQty, lineId }: { orderId: string; invoice: string; issueCode: string; productId?: string | null; productSku?: string | null; openDemand: number; queueUnits: number; reservationUnits: number; containerUnits: number; shippedQty: number; lineId?: string }) {
  const [open, setOpen] = useState(false);
  if (issueCode === "ACTIVE_DUPLICATE_PARENT_CONFLICT") return <div className="flex flex-wrap gap-2"><a href={`/orders/${orderId}#items`} className="btn-secondary inline-flex text-xs">View Order</a><a href={`/orders/${orderId}?investigate=duplicate-parent#items`} className="btn-secondary inline-flex text-xs">Investigate</a></div>;
  if (issueCode === "QBO_FORWARD_MAPPING_REVIEW" || issueCode === "QBO_FORWARD_IDENTITY_REVIEW") return <div className="flex flex-wrap gap-2"><a href="/orders/import-assign" className="btn-secondary inline-flex text-xs">Open Intake Review</a></div>;
  if (issueCode === "QBO_FORWARD_INTAKE_UNAVAILABLE") return <div className="flex flex-wrap gap-2"><a href="/settings" className="btn-secondary inline-flex text-xs">Open QuickBooks Settings</a></div>;
  if (issueCode === "VOIDED_ACTIVE") {
    return <div className="flex flex-wrap gap-2"><button type="button" className="btn-primary inline-flex text-xs" onClick={() => setOpen(true)}>Cancel in ERP</button><a href={`/orders/${orderId}${lineId ? `#line-${lineId}` : "#items"}`} className="btn-secondary inline-flex text-xs">View order</a>{open ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-xl border border-[#dbe3ee] bg-white p-5 shadow-2xl"><h2 className="text-lg font-semibold text-[#111827]">Cancel Invoice #{invoice}?</h2><p className="mt-2 text-sm text-[#475569]">QuickBooks reports this invoice as Voided.</p><div className="mt-4 rounded-lg border border-[#f5c26b] bg-[#fffaf0] p-3 text-sm text-[#334155]"><p className="font-semibold">This will affect:</p><ul className="mt-2 list-disc pl-5"><li>Open customer demand removed: {openDemand}</li><li>Queue units released: {queueUnits}</li><li>Warehouse reservations released: {reservationUnits}</li><li>Incoming/container allocations released: {containerUnits}</li><li>Existing shipped quantity preserved: {shippedQty}</li></ul><p className="mt-3 font-semibold">Will NOT change:</p><p className="mt-1">Physical ON_FLOOR inventory, container quantities, receiving history, completed shipments, previous inventory transactions, or fulfilled history.</p></div><div className="mt-4 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Keep open</button><form action={cancelVoidedOrderAction}><input type="hidden" name="orderId" value={orderId} /><input type="hidden" name="confirmation" value="CONFIRM_CANCEL_VOIDED" /><button type="submit" className="btn-danger">Confirm Cancellation</button></form></div></div></div> : null}</div>;
  }
  if (issueCode === "QUEUE_COUNT_MISMATCH" || issueCode === "QUEUE_POSITION_MISSING") return <div className="flex flex-wrap gap-2"><form action={rebuildExceptionQueueAction}><input type="hidden" name="product_id" value={productId ?? ""} /><button type="submit" className="btn-secondary inline-flex text-xs" disabled={!productId}>Rebuild Queue</button></form><a href={`/orders/${orderId}${lineId ? `#line-${lineId}` : "#items"}`} className="btn-secondary inline-flex text-xs">View order</a></div>;
  if (issueCode === "UNMAPPED_PHYSICAL_LINE") return <div className="flex flex-wrap gap-2"><a href={`/product-mappings?source_sku=${encodeURIComponent(productSku ?? "")}&order_id=${encodeURIComponent(orderId)}`} className="btn-secondary inline-flex text-xs">Map Product</a><a href={`/orders/${orderId}${lineId ? `#line-${lineId}` : "#items"}`} className="btn-secondary inline-flex text-xs">View order</a></div>;
  const action = issueCode.includes("DUPLICATE") ? "Review Duplicate" : "Investigate";
  return <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary inline-flex text-xs" disabled>{action}</button><a href={`/orders/${orderId}${lineId ? `#line-${lineId}` : "#items"}`} className="btn-secondary inline-flex text-xs">View order</a></div>;
}
