import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdminUnlockedForUser } from "@/lib/admin-access";
import { requireUser } from "@/lib/auth";
import { previewVerifiedQboFirstPaymentBackfill } from "@/lib/quickbooks/first-payment-backfill";

export default async function QboFirstPaymentBackfillPreviewPage({ searchParams }: { searchParams: Promise<{ run?: string }> }) {
  const user = await requireUser();
  if (!await isAdminUnlockedForUser(user.id)) redirect("/settings?error=Admin+code+required");
  if ((await searchParams).run !== "1") return <div className="space-y-4"><h1 className="text-3xl">Verified First-Payment Backfill Preview</h1><p className="text-sm text-[#5a5a5a]">Read-only. Only active canonical demand with exactly one linked QBO Payment is proposed.</p><div className="flex gap-2"><Link href="/settings/qbo-first-payment-backfill?run=1" className="btn-primary">Run Preview</Link><Link href="/settings/qbo-first-payment-audit" className="btn-secondary">Back to Audit</Link></div></div>;
  const preview = await previewVerifiedQboFirstPaymentBackfill();
  return <div className="space-y-5"><div><h1 className="text-3xl">Verified First-Payment Backfill Preview</h1><p className="text-sm text-[#5a5a5a]">Read-only proposal generated {preview.generatedAt}. Execution is disabled.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="card p-3"><p className="text-sm text-[#5a5a5a]">Proposed Orders</p><p className="text-2xl font-semibold">{preview.summary.proposedOrders}</p></div><div className="card p-3"><p className="text-sm text-[#5a5a5a]">Proposal Hash</p><p className="break-all font-mono text-xs">{preview.proposalHash}</p></div></div><section className="card overflow-x-auto p-4"><table className="w-full min-w-[1300px] text-left text-sm"><thead><tr className="border-b"><th>Shipping Order ID</th><th>Customer</th><th>Invoice</th><th>Current First Paid</th><th>Proposed First Paid</th><th>Affected SKU(s)</th><th>Current Position</th><th>Projected Position</th><th>Evidence</th><th>Proposal Hash</th></tr></thead><tbody>{preview.proposals.map((proposal) => <tr key={proposal.shippingOrderId} className="border-b"><td className="py-2 font-mono text-xs">{proposal.shippingOrderId}</td><td>{proposal.customer}</td><td>{proposal.invoice}</td><td>Not recorded</td><td>{proposal.proposedFirstPaymentAt}</td><td>{proposal.skuImpacts.map((impact) => impact.sku ?? "-").join(", ")}</td><td>{proposal.skuImpacts.map((impact) => `#${impact.currentPosition}`).join(", ")}</td><td>{proposal.skuImpacts.map((impact) => `#${impact.projectedPosition}`).join(", ")}</td><td>VERIFIED</td><td className="font-mono text-xs">{proposal.proposalHash}</td></tr>)}</tbody></table></section><Link href="/settings/qbo-first-payment-audit" className="btn-secondary">Back to Audit</Link></div>;
}